version: "3.9"

services:
  frontend:
    build:
      context: ../triply-app
    image: triply-frontend:latest
    networks:
      - triply-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

  backend:
    build:
      context: ../triply-api
    image: triply-backend:latest
    networks:
      - triply-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: triply_user
      POSTGRES_PASSWORD: triply_password
      POSTGRES_DB: triply_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - triply-network

networks:
  triply-network:
    driver: overlay

volumes:
  db-data:
