version: "3.9"

services:
  frontend:
    image: darrennnnlim/triply-frontend:latest
    networks:
      - triply-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80"  # Map host port 8081 to container port 4200

  backend:
    image: darrennnnlim/triply-backend:latest
    networks:
      - triply-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - database
    ports:
      - "8082:8080" # Publish port 8080 for the backend

  database:
    image: postgres:16
    networks:
      - triply-network
    environment:
      POSTGRES_USER: triply_user
      POSTGRES_PASSWORD: triply_password
      POSTGRES_DB: triply
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U triply_user"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  triply-network:
    driver: overlay

volumes:
  db-data:
