version: "3.9"

services:
  frontend:
    image: triply-frontend:latest
    networks:
      - triply-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8081:80" # Publish port 80 for the frontend

  backend:
    image: triply-backend:latest
    networks:
      - triply-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8082:8080" # Publish port 8080 for the backend

  database:
    image: postgres:16
    networks:
      - triply-network
    environment:
      POSTGRES_USER: triply_user
      POSTGRES_PASSWORD: triply_password
      POSTGRES_DB: triply_db
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  triply-network:
    driver: overlay

volumes:
  db-data:
